Repository ChandelAnish/fusionFLOW, pull requests merged in 2024-10, with the labels that each got.

#18 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc-ext, level1, hacktoberfest-accepted

#96 Update Readme.md
  README.md
Labels: documentation, enhancement, gssoc-ext, level1

#99 Update connectDB.js
  server/db/connectDB.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#100 Update index.html
  client/index.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#101 Update router.js
  server/router/router.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#102 Update index.html
  auth/signup/index.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3
